# Specify a base image
FROM node:alpine

WORKDIR /usr/api/

# Install some dependencies
COPY package.json .

RUN apk add git
RUN git init

RUN yarn

COPY . .
EXPOSE 3000

# Default command
CMD ["yarn", "devstart"]